package cl.mp.rgp.common.model;

/**
 * This class was automatically generated by the data modeler tool.
 */
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;

public class PerfilamientoUsuarios implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Integer fiscaliaId;

	private java.lang.String regionId;

	@org.kie.api.definition.type.Label("Zona Id")
	private java.lang.Integer zonaId;

	private java.lang.String modulo;

	public PerfilamientoUsuarios() {
	}

	public java.lang.Integer getFiscaliaId() {
		return this.fiscaliaId;
	}

	public void setFiscaliaId(java.lang.Integer fiscaliaId) {
		this.fiscaliaId = fiscaliaId;
	}

	public java.lang.String getRegionId() {
		return this.regionId;
	}

	public void setRegionId(java.lang.String regionId) {
		this.regionId = regionId;
	}

	public java.lang.Integer getZonaId() {
		return this.zonaId;
	}

	public void setZonaId(java.lang.Integer zonaId) {
		this.zonaId = zonaId;
	}

	public java.lang.String getModulo() {
		return this.modulo;
	}

	public void setModulo(java.lang.String modulo) {
		this.modulo = modulo;
	}

	public PerfilamientoUsuarios(java.lang.Integer fiscaliaId,
			java.lang.String regionId, java.lang.Integer zonaId,
			java.lang.String modulo) {
		this.fiscaliaId = fiscaliaId;
		this.regionId = regionId;
		this.zonaId = zonaId;
		this.modulo = modulo;
	}
	
	@Override
    public String toString() {
		ObjectMapper mapper = new ObjectMapper();
		String json = null;
		try {
			json = mapper.writeValueAsString(this);
		} catch (JsonProcessingException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
        return json;
    }

}
